services:
  postgresdb:
    image: postgres:14
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=dummy_db
      - POSTGRES_USER=postgres
  web:
    image: server01:tag01
    ports:
      - 3000:3000
    depends_on:
      - postgresdb